apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  # Запускается с 2-я экземплярами подов
  replicas: 2
  minReadySeconds: 15
  strategy:
    # Стратегия обеспечивает нулевое время простоя системы при обновлении
    type: RollingUpdate
    rollingUpdate:
      # После завершения работы пода ещё один будет выполняться
      maxUnavailable: 1
      # При переходе на новую версию программы, мы можем добавить в кластер ещё один под
      maxSurge: 1
  selector:
    matchLabels:
      app: app
  # Объект задаёт шаблон пода, который будет использовать для создания новых подов
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: znhv/app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        resources:
          # Установка лимита памяти и CPU
          limits:
            cpu: 1000m
            memory: 128Mi
          # Установка запроса памяти и CPU
          requests:
            cpu: 100m
            memory: 128Mi