apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 2 # Запускается с 2-я экземплярами подов
  minReadySeconds: 15
  strategy:
    type: RollingUpdate # Стратегия обеспечивает нулевое время простоя системы при обновлении
    rollingUpdate:
      maxUnavailable: 1 # После завершения работы пода ещё один будет выполняться
      maxSurge: 1 # При переходе на новую версию программы, мы можем добавить в кластер ещё один под
  selector:
    matchLabels:
      app: app
  template: # Объект задаёт шаблон пода, который будет использовать для создания новых подов
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: znhv/app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        resources:
          limits: # Установка лимита памяти и CPU
            cpu: "1"
            memory: "128Mi"
          requests: # Установка запроса памяти и CPU
            cpu: "0.1"
            memory: "128Mi"