apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app
  # Минимальное количество реплик
  minReplicas: 1
  # Максимальное количество реплик
  maxReplicas: 10
  # Средняя загрузка CPU, если нагрузка превысит 50%, то модуль будет масштабироваться
  targetCPUUtilizationPercentage: 50
