apiVersion: v1
kind: Service
metadata:
  name: app-service-lb
spec:
  selector:
    # Объект, содержащий сведения о том, с какими подами должен работать сервис
    app: app
  ports:
    # Протокол, используемый сервисом
  - protocol: TCP
    # Порт, по которому сервис принимает запросы
    port: 8080
    # Порт, на который перенаправляются входящие запросы
    targetPort: 5000
  # Тип ресурса для балансировки нагрузки между подами
  type: LoadBalancer
